### ISSUE TITLE
Help me..

### ISSUE THREAD

**Issue by imsrikant** [diesire/git_bash_windows_powerline#12]
# How I can resolve this... ??
![image](https://user-images.githubusercontent.com/52560067/202413798-283bfd92-5f3a-408f-9904-abe3ec583d57.png)

**Comment by akannan2987** [comment]
Same here i also get the similar message:

![Screenshot 2022-11-23 102912](https://user-images.githubusercontent.com/56790987/203512235-56baa719-152b-4278-9c6d-f12a4ffadd6f.png)

**Comment by imsrikant** [comment]
# Use oh my posh
![image](https://user-images.githubusercontent.com/52560067/203667872-271bb19b-5eb0-495a-8ee0-e16ff117b748.png)
